
module.exports = {
  event: 'remove',
  handle: async ({ api, event }) => {
    const removedMembers = event.participants;
    const funnyGoodbyes = [
      "😢 @NAME গ্রুপ ছেড়ে চলে গেলো… এখন কারে দিয়ে meme বানাবো বলো!",
      "😂 @NAME চলে গেলো… সবাই clap clap 👏",
      "💔 আহারে... @NAME চলে গেলো, এখন কে আমাদেরকে ট্রল করবে?",
      "🍵 @NAME গ্রুপ ছেড়ে গেছে… সবাই এক কাপ চা খাইয়া শোক পালন করো ☕",
      "🕊️ শান্তিতে যাস @NAME, গ্রুপের স্মৃতিগুলো ভুলিস না 😌",
      "🚪 দরজা খোলা হলো, আর @NAME বেরিয়ে গেলো... গুডবাই!",
      "😂 গ্রুপ quiet হয়ে যাবে মনে হয়… কারণ @NAME তো নাই!",
      "🎭 @NAME ছিলো গ্রুপের আসল কমেডিয়ান, আজকে গ্রুপের নাটক শেষ 😢",
      "📉 ব্রেকিং নিউজ: @NAME চলে যাওয়াতে গ্রুপের ভিউয়ারশিপ 70% কমে গেছে 📉",
      "🥀 ফুল ফুরায়, বন্ধুত্বও… আজকে @NAME গ্রুপ ছেড়ে দিলো 💐",
      "🚮 @NAME কে গ্রুপ থেকে uninstall করা হলো 🗑️",
      "😈 গ্রুপ থেকে পালাইছে @NAME, এখন ওর ghost account আসবে নিশ্চিত 👻",
      "📦 @NAME কে গ্রুপ থেকে parcel করে পাঠানো হলো কুরিয়ারে 📬",
      "🎮 Game Over! @NAME disconnected from গ্রুপ 🎮",
      "🧹 গ্রুপের ঝাড়ু operation এ @NAME কে বের করা হলো 🤣",
      "⚡ @NAME লিভ দিয়ে গেলো, গ্রুপের চার্জ হঠাৎ 50% নেমে গেলো 🔋",
      "🎤 আজকের গানের লিরিক: “@NAME ছাড়া গ্রুপ ফাঁকা ফাঁকা লাগে…” 🎶",
      "😎 গ্রুপ ছেড়ে গেলেও @NAME নিয়ে meme বানানো চালু থাকবে 🔥",
      "🍔 ফ্রি বার্গার পাইনি দেখে @NAME রাগ করে গ্রুপ ছাড়লো 🍟",
      "🚨 দৃষ্টি আকর্ষণ: @NAME এখন আর গ্রুপের নাগরিক না 🚧",
      "🥶 @NAME এর লিভ দেখে পুরো সার্ভার হ্যাং হয়ে গেলো ❄️",
      "🎉 সবাই clap clap 👏 কারণ @NAME free হয়ে গেলো গ্রুপ থেকে 😜",
      "📢 জরুরি সংবাদ: @NAME গ্রুপ ত্যাগ করায় এখন থেকে গ্রুপে কম নাটক হবে 🤭",
      "🛑 STOP! @NAME has left the chat. Proceed with caution 🚷",
      "🤔 এখন কে admin এর সাথে ঝগড়া করবে? @NAME তো নাই 😅",
      "🍕 পার্টি খাওয়াতে না পেরে @NAME পালিয়ে গেলো গ্রুপ থেকে 🤣",
      "👋 গুডবাই @NAME… ফিরে আসবি তো? না forever block দিলি 😭",
      "🎬 Drama শেষ! গ্রুপের সিনেমার নায়ক @NAME চলে গেলো 🎥",

      "🤡 @NAME কে গ্রুপ থেকে বের করা হলো, বাসায় গিয়ে নুডলস খেতে খেতে কাঁদবে এখন!",
      "😎 বাই বাই @NAME — চলে গেলেও তোকে নিয়ে roast চলবেই!",
      "🥲 সবাই একটু হাত নাড়াও 👉👋… @NAME গ্রুপ ত্যাগ করলো!",
      "🛫✈️ @NAME ভিসা পেয়ে গ্রুপ ছেড়ে বিদেশ চলে গেলো নাকি?",
      "🤣 আজকের দুঃসংবাদ: @NAME গ্রুপ থেকে বিদায় নিলো, গ্রুপের drama rating ৫০% কমে গেলো!",
        "😢 আজকের ব্রেকিং নিউজ: @NAME চলে গেলো… এখন গ্রুপে আর মশলাদার গসিপ হবে না!",
"🥲 আহারে, @NAME ছাড়া গ্রুপের vibe একদম down 📉",
"🤣 সবাই খুশি, কারণ @NAME leave দিয়ে গ্রুপের volume কমে গেলো 😂",
"🤡 @NAME চলে গেছে… কিন্তু screenshot থেকে যাবে চিরদিন 🤭",
"📢 দৃষ্টি আকর্ষণ: @NAME এর exit interview কালকে হবে গ্রুপে 😜",
"🛑 Attention! @NAME officially logged out from গ্রুপ 🔒",
"👀 @NAME গেলো বটে, কিন্তু ওর স্টিকারগুলো রয়ে গেলো 🙄",
"🍟 আজকে থেকে গ্রুপে french fry কমে গেলো… কারণ @NAME নাই 🍔",
"🎯 Mission Failed! @NAME left the operation গ্রুপ 🎮",
"👋 টাটা বাই বাই, @NAME – তোমাকে ছাড়া গ্রুপ একেবারে boring 💤",
"😎 যাও রে @NAME, কিন্তু meme দিয়ে তোমার ইতিহাস বেঁচে থাকবে 🔥",
"🚑 জরুরি সংবাদ: @NAME ছেড়ে যাওয়াতে গ্রুপের হাসির ডোজ কমে গেছে 💊",
"🎭 গ্রুপের নাটকের নায়ক @NAME চলে গেলো, কিন্তু audience আছি আমরা 🤣",
"💔 অনেক কষ্টে announce করছি… @NAME আর গ্রুপে নাই 😢",
"🍕 @NAME গেলো মানে এখন পার্টি cancel… sobai go home 🏠",
"🪦 RIP @NAME এর membership – gone but not forgotten ⚰️",
"🎬 @NAME left the stage… গ্রুপের মুভি এখনও চলবে 🎥",
"🤖 Update: @NAME uninstall complete, গ্রুপ reboot হচ্ছে 🔄",
"🧨 Breaking Bombshell: @NAME left… drama meter 200% কমে গেলো 💣",
"🕊️ @NAME চলে গেলো শান্তির খোঁজে, গ্রুপে এখন নীরবতা 😌",
"🤔 ভাবছি, @NAME আসলে গ্রুপ ছেড়েছে নাকি আমাদেরকে ignore দিছে? 🤨",
"🥳 Congratulations! @NAME finally escaped from গ্রুপ 🤣",
"🚀 @NAME গ্রুপ ছেড়ে interstellar trip এ গেলো 🚀",
"📦 Delivery complete: @NAME successfully shipped out of গ্রুপ 📤",
"🌚 @NAME নাই… গ্রুপের রাতগুলো এখন শান্ত হবে 🌙",
"🎶 গান পরিবর্তন: 'Chole Gecho Tumi...' dedicated to @NAME 🎤",
"⚡ Server Alert: @NAME disconnected, bandwidth free হলো ⚡",
"🥴 ওহো! @NAME তো পালাইছে, এখন gossip কম হবে 🤐",
"👑 গ্রুপের VIP @NAME চলে গেলো, এখন কে rule ভাঙবে? 👮",
"😂 গ্রুপ থেকে @NAME কে delete করা হলো… undo button নাই 🤣",
"🐸 Frog squad বলছে bye bye to @NAME 🐸",
"🍻 Cheers! সবাই celebrate করো, @NAME finally মুক্তি পেলো 🥂",
"🕹️ Controller unplugged – @NAME out of game 🎮",
"😇 গ্রুপ থেকে মুক্তি পেয়ে এখন @NAME স্বর্গে শান্তি পাচ্ছে ☁️",
"📱 Notification: '@NAME left the group' – আরে ভাই, জানিই তো! 🤳",
"🌍 @NAME চলে গেলো নিজের নতুন world explore করতে 🌎",
"🚪 Door বন্ধ হলো, আর @NAME forever চলে গেলো 🚷",
"🥶 ঠাণ্ডা খবর: @NAME ছাড়া গ্রুপ বরফ হয়ে গেছে ❄️",
"🎉 Surprise! আজকের lucky leaver হলো @NAME 🎰",
"🛫 প্লেন ধরলো @NAME – next stop: গ্রুপ ছাড়া জীবন ✈️",
"🤣 সবাই relief পেয়েছে, কারণ @NAME আর নেই 👻",
"🔥 Drama King/Queen @NAME left the building 💃🕺",
"🎤 Mic drop moment: @NAME out of গ্রুপ 🎙️",
"📖 History Update: আজকের দিনে @NAME গ্রুপ ছেড়ে গিয়েছিল 📚",
"🕹️ Level Over! @NAME has exited গ্রুপের গেম 🎮",
"👻 এখন থেকে @NAME শুধু meme-এই বাঁচবে 👾",
"🍫 গ্রুপ থেকে মিষ্টি মানুষটা চলে গেলো – Bye Bye @NAME 🍬",
    "🚨 Emergency Alert: @NAME এর অভাবে গ্রুপ silent mode এ চলে গেলো 🔕"
    ];

    for (const member of removedMembers) {
      const msg = funnyGoodbyes[Math.floor(Math.random() * funnyGoodbyes.length)]
        .replace("@NAME", `@${member.split('@')[0]}`);

      await api.sendMessage(event.id, {
        text: msg,
        mentions: [member]
      });
    }
  }
};
